"""Config Generator — Converts approved discovery suggestions into pipeline-ready YAML.
Output: config/tables/{asset}.yaml compatible with bt_df_lkhouse_fw.
DQ rules are inherited from BDE definitions (define once, apply everywhere)."""
import yaml
from typing import Optional
from discovery.engine.suggester import DiscoverySuggestion
from discovery.engine.dq_inheritance import DQInheritanceEngine

# Global DQ inheritance engine
_dq_engine = DQInheritanceEngine()


class ConfigGenerator:
    """Generates bt_df_lkhouse_fw compatible table YAML from approved suggestions."""

    def generate(self, suggestion: DiscoverySuggestion,
                 approved_fields: Optional[list[str]] = None) -> str:
        """Generate YAML config from a discovery suggestion.
        If approved_fields is None, all fields are assumed approved."""
        fields = suggestion.fields
        if approved_fields:
            fields = [f for f in fields if f.field_name in approved_fields]

        config = {
            "table": suggestion.asset_name,
            "description": self._build_description(suggestion),
            "source": f"landing/{suggestion.asset_name}",
            "source_format": suggestion.source_format,
            "primary_key": suggestion.primary_key or self._guess_pk(fields),
            "dedup_order_by": "ingestion_ts DESC",
        }

        # DQ Rules (from field suggestions + inherited from BDEs)
        dq_rules = self._build_dq_rules(fields)
        if dq_rules:
            config["dq_rules"] = dq_rules

        # Enrich with BDE-level DQ inheritance
        config = _dq_engine.enrich_from_suggestion(config, suggestion)

        # PII fields
        pii_fields = [f.field_name for f in fields if f.is_pii]
        if pii_fields:
            config["pii_fields"] = pii_fields

        # Type overrides (for numeric fields that might arrive as string)
        type_overrides = {}
        for f in fields:
            if f.field_type in ("double", "decimal", "float", "integer", "int"):
                type_overrides[f.field_name] = "double" if f.field_type in ("decimal", "float") else f.field_type
        if type_overrides:
            config["type_overrides"] = type_overrides

        # Schema evolution
        if suggestion.schema_evolution:
            config["schema_evolution"] = suggestion.schema_evolution
        else:
            config["schema_evolution"] = {
                "allowed": ["add_column", "type_widen"],
                "blocked": ["drop_column", "type_narrow"],
            }

        # Metadata (for lineage/audit)
        config["_metadata"] = {
            "discovered_at": suggestion.discovered_at,
            "business_application": suggestion.business_application_name,
            "data_domain": suggestion.data_domain,
            "discovery_mode": suggestion.mode,
        }

        # Format as YAML with header comment
        header = (
            f"# {suggestion.asset_name}.yaml — Auto-generated by Semantic Discovery\n"
            f"# Business Application: {suggestion.business_application_name or 'TBD'}\n"
            f"# Data Domain: {suggestion.data_domain or 'TBD'}\n"
            f"# Discovery Mode: {suggestion.mode}\n"
            f"# Generated: {suggestion.discovered_at}\n"
        )
        yaml_body = yaml.dump(config, default_flow_style=False, sort_keys=False, allow_unicode=True)
        return header + yaml_body

    def generate_catalog_entry(self, suggestion: DiscoverySuggestion) -> dict:
        """Generate a catalog-ready metadata entry (for Dataplex/OpenMetadata)."""
        entry = {
            "asset_name": suggestion.asset_name,
            "business_application": suggestion.business_application_name,
            "data_domain": suggestion.data_domain,
            "classification": self._highest_classification(suggestion),
            "owner": "TBD — assign data steward",
            "fields": [],
        }

        for f in suggestion.fields:
            field_entry = {
                "name": f.field_name,
                "type": f.field_type,
                "business_term": f.linked_term_name,
                "information_type": f.information_type,
                "classification": f.classification,
                "is_pii": f.is_pii,
                "dq_rules": f.dq_rules,
            }
            if f.reference_code_set:
                field_entry["reference_code_set"] = f.reference_code_set
            if f.fk_reference:
                field_entry["foreign_key"] = f.fk_reference
            entry["fields"].append(field_entry)

        return entry

    def _build_description(self, suggestion: DiscoverySuggestion) -> str:
        parts = [suggestion.asset_name.replace("_", " ").title()]
        if suggestion.business_application_name:
            parts.append(f"({suggestion.business_application_name})")
        return " ".join(parts)

    def _build_dq_rules(self, fields) -> dict:
        dq = {}

        # not_null
        not_null_fields = [f.field_name for f in fields if f.dq_rules.get("not_null")]
        if not_null_fields:
            dq["not_null"] = not_null_fields

        # positive
        positive_fields = [f.field_name for f in fields if f.dq_rules.get("positive")]
        if positive_fields:
            dq["positive"] = positive_fields

        # unique
        unique_fields = [f.field_name for f in fields if f.dq_rules.get("unique")]
        if unique_fields:
            dq["unique"] = unique_fields

        # accepted_values
        accepted = {}
        for f in fields:
            if f.accepted_values:
                # Don't set accepted_values for boolean or numeric fields
                if f.field_type in ("boolean", "integer", "decimal", "double", "float", "int"):
                    continue
                accepted[f.field_name] = f.accepted_values
            elif f.dq_rules.get("accepted_values"):
                if f.field_type in ("boolean", "integer", "decimal", "double", "float", "int"):
                    continue
                accepted[f.field_name] = f.dq_rules["accepted_values"]
        if accepted:
            dq["accepted_values"] = accepted

        # range checks
        ranges = {}
        for f in fields:
            if f.dq_rules.get("range"):
                ranges[f.field_name] = f.dq_rules["range"]
        if ranges:
            dq["range"] = ranges

        # format checks
        formats = {}
        for f in fields:
            if f.dq_rules.get("format"):
                formats[f.field_name] = f.dq_rules["format"]
        if formats:
            dq["format"] = formats

        return dq

    def _guess_pk(self, fields) -> str:
        """Fallback PK guess if none explicitly identified."""
        for f in fields:
            if f.is_key_candidate:
                return f.field_name
        # Last resort: first field ending in _id
        for f in fields:
            if f.field_name.endswith("_id"):
                return f.field_name
        return fields[0].field_name if fields else "id"

    def _highest_classification(self, suggestion: DiscoverySuggestion) -> str:
        classifications = [f.classification for f in suggestion.fields]
        if "PII" in classifications or "PHI" in classifications:
            return "PII"
        if "Sensitive" in classifications:
            return "Sensitive"
        return "Internal"
